# Default values for public-people-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 2
image:
  repository: coco/public-people-api
  pullPolicy: IfNotPresent
cache_duration: 10m
resources:
 requests:
   memory: 12Mi
 limits:
   memory: 72Mi


