// Code generated by mockery v1.0.0
package people

import mock "github.com/stretchr/testify/mock"
import v1_1 "github.com/Financial-Times/go-fthealth/v1_1"

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

// Healthchecks provides a mock function with given fields:
func (_m *MockDriver) Healthchecks() []v1_1.Check {
	ret := _m.Called()

	var r0 []v1_1.Check
	if rf, ok := ret.Get(0).(func() []v1_1.Check); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1_1.Check)
		}
	}

	return r0
}

// Read provides a mock function with given fields: id, transactionID
func (_m *MockDriver) Read(id string, transactionID string) (Person, bool, error) {
	ret := _m.Called(id, transactionID)

	var r0 Person
	if rf, ok := ret.Get(0).(func(string, string) Person); ok {
		r0 = rf(id, transactionID)
	} else {
		r0 = ret.Get(0).(Person)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = rf(id, transactionID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(id, transactionID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
