version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
      - image: neo4j:3.1.0-enterprise
        environment:
          NEO4J_AUTH: none
          NEO4J_HEAP_MEMORY: 256
          NEO4J_CACHE_MEMORY: 256M

    working_directory: /go/src/github.com/Financial-Times/public-people-api
    environment:
      NEO4J_TEST_URL: "http://localhost:7474/db/data/"
      CIRCLE_TEST_REPORTS: /tmp/test-reports
      CIRCLE_ARTIFACTS: /tmp/artifacts

    steps:
        - checkout
        - run:
            name: Make /go owned by circleci
            command: sudo chown -R circleci:circleci /go
        - run:
            name: Download dependencies
            command: |
                go get -u github.com/kardianos/govendor
                go get -u github.com/jstemmer/go-junit-report
                go get -u github.com/mattn/goveralls
        - run:
            name: Sync vendored packages
            command: govendor sync -v
        - run:
            name: Build service
            command: govendor build -v
        - run:
            name: Wait for Neo to be available
            command: wget --retry-connrefused --no-check-certificate -T 60 $NEO4J_TEST_URL; curl $NEO4J_TEST_URL
        - run:
            name: Run tests and coverage
            command: |
                mkdir -p $CIRCLE_TEST_REPORTS/golang
                mkdir -p $CIRCLE_ARTIFACTS
                govendor test -race -v -coverprofile=$CIRCLE_ARTIFACTS/profile.out +local | go-junit-report > $CIRCLE_TEST_REPORTS/golang/junit.xml
                sed -i "/_mock/d" $CIRCLE_ARTIFACTS/profile.out
        - run:
            name: Upload to coveralls
            command: goveralls -coverprofile=$CIRCLE_ARTIFACTS/profile.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
        - store_test_results:
            path: /tmp/test-reports
        - store_artifacts:
            path: /tmp/artifacts
            destination: build
