version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
      - image: neo4j:3.1.0-enterprise
        environment:
          NEO4J_AUTH: none
          NEO4J_HEAP_MEMORY: 256
          NEO4J_CACHE_MEMORY: 256M

    working_directory: /go/src/github.com/Financial-Times/public-people-api
    environment:
      NEO4J_TEST_URL: "http://localhost:7474/db/data/"
      CIRCLE_TEST_REPORTS: /tmp/test-reports
      CIRCLE_ARTIFACTS: /tmp/artifacts

    steps:
      - checkout
      - run:
          name: Make go get work
          command: sudo chown -R circleci:circleci /go/src
      - run:
          name: Create test folder
          command: mkdir -p $CIRCLE_TEST_REPORTS
      - run: |
          go get -u github.com/kardianos/govendor
      - run: |
          govendor sync
      - run: |
          govendor build -v
      - run:
          wget --retry-connrefused --no-check-certificate -T 60 $NEO4J_TEST_URL; curl $NEO4J_TEST_URL
      - run: |
          go get -u github.com/jstemmer/go-junit-report
          go get -u github.com/mattn/goveralls
          wget https://raw.githubusercontent.com/Financial-Times/cookiecutter-upp-golang/master/coverage.sh && chmod +x coverage.sh
      - run: |
          mkdir -p $CIRCLE_TEST_REPORTS/golang
          mkdir -p $CIRCLE_ARTIFACTS
          govendor test -race -v +local | go-junit-report > $CIRCLE_TEST_REPORTS/golang/junit.xml
          ./coverage.sh
      - run: |
          goveralls -coverprofile=$CIRCLE_ARTIFACTS/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-reports

      - store_artifacts:
          path: /tmp/artifacts
          destination: build
