version: 2.1
orbs:
  ft-golang-ci: financial-times/golang-ci@1.0.0
workflows:
  test-and-build-docker:
    jobs:
      - ft-golang-ci/build-and-test:
          name: build-and-test-project
          golangci-lint-version: "v1.23.6"
      - ft-golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build-and-test-project
  snyk-scanning:
    jobs:
      - ft-golang-ci/scan:
          name: scan-dependencies
          context: org-global
